# Generated by Django 3.1.1 on 2020-12-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã tài khoản')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('name', models.CharField(max_length=50, verbose_name='Họ tên')),
                ('password', models.CharField(max_length=15, verbose_name='Mật khẩu')),
                ('gmail', models.CharField(max_length=40, verbose_name='Gmail')),
                ('sex', models.CharField(max_length=5, verbose_name='Giới tính')),
                ('image', models.ImageField(upload_to='static/images_staff', verbose_name='hình ảnh')),
                ('birthday', models.DateField(verbose_name='Ngày sinh')),
                ('lever', models.IntegerField(null=True, verbose_name='Loại tài khoản')),
                ('status', models.IntegerField(null=True, verbose_name='Trạng thái tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='giá dùng')),
                ('description', models.CharField(max_length=500, verbose_name='Mô tả')),
                ('date', models.DateField(verbose_name='Thời gian đăng')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại liên hệ')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='hình ảnh')),
                ('status', models.IntegerField(verbose_name='Tình trạng phòng')),
                ('view', models.IntegerField(verbose_name='số lượt xem')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account', verbose_name='Mã bài đăng')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='Tiền thanh toán')),
                ('day', models.DateField(verbose_name='Thời gian')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.post', verbose_name='Bài đăng')),
            ],
        ),
    ]
