# Generated by Django 3.1.1 on 2020-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
    ]
